server:
  port: 9990
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ali_vlizadeh@25975800
    url: jdbc:mysql://localhost:3306/City
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true